version: '3'

volumes:
  # for persistence between restarts
  postgres_data: {}
  rabbitmq_data: {}

services:
  db:
    image: postgres
    restart: always
    ports:
      - "30000:5432"
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: nestbook
    volumes:
        - postgres_data:/var/lib/postgresql/data
  # redis:
  #     image: redis
  #     restart: always
  #     ports:
  #       - "30001:6379"
  rabbitmq:
    image: rabbitmq
    ports:
      - "25672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/bitnami
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    depends_on:
      - db
      # - redis
      - rabbitmq
    links:
      - db
      # - redis
      - rabbitmq
    environment:
      DB_HOST: db
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: nestbook
      POSTGRES_PORT: 5432
      PORT: 3000
      # REDIS_URL: redis://redis:6379
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      npm run start:dev
